version: '3.8'

services:
  app:
    build:
      context: .
      args:
        POCKETBASE_VERSION: "0.40.4"
    image: ghcr.io/s4ndyp/financepro:latest
    container_name: financepro-container
    restart: unless-stopped
    ports:
      - "7104:8090"
    volumes:
      - pocketbase_data:/app/pb_data

volumes:
  pocketbase_data:
